antipodes = [ ['Christchurch, New Zealand', 'A Coruna, Spain'],
['Hamilton, New Zealand', 'Cordoba, Spain'],
['Hong Kong', 'La Quiaca, Argentina'],
['Junin, Argentina', 'Lianyungang, China'],
['Padang, Indonesia', 'Esmeraldas, Ecuador'],
['Palembang, Indonesia', 'Neiva, Colombia'],
['Rafaela, Argentina', 'Wuhu, China'],
['Segovia, Spain', 'Masterton, New Zealand'],
['Tauranga, New Zealand', 'Jaen, Spain'],
['Ulan Ude, Russia', 'Puerto Natales, Chile'],
['Valdivia, Chile', 'Wuhai, China'],
['Whangarei, New Zealand', 'Tangier, Morocco'],
['Xian, China', 'Santiago, Chile'],
['Auckland, New Zealand', 'Seville, Spain'],
['Auckland, New Zealand', 'Setenil de las Bodegas, Spain'],
['Auckland, New Zealand', 'Malaga, Spain'],
['Tianjin, China', 'Bahia Blanca, Argentina'],
['Shanghai, China', 'Salto, Uruguay'],
['Taipei, Taiwan', 'Asuncion, Paraguay'],
['Nanjing, China', 'Rosario, Argentina'],
['Montpellier, France', 'Waitangi, New Zealand'],
['Beijing, China', 'Bahía Blanca, Argentina'],
['Beijing, China', 'Buenos Aires, Argentina'],
['Shanghai, China', 'Buenos Aires, Argentina'],
['Bogota, Colombia', 'Jakarta, Indonesia'],
['Guayaquil, Ecuador', 'Medan, Indonesia'],
['Phnom Penh, Cambodia', 'Lima, Peru'],
['Dili, Timor-Leste', 'Paramaribo, Suriname'],
['Irkutsk, Russia', 'Punta Arenas, Chile'],
['Tongchuan, China', 'Licanten, Chile'],
['Suva, Fiji', 'Timbuktu, Mali'],
['Canberra, Australia', 'Azores, Portugal'],
['Melbourne, Australia', 'Azores, Portugal'],
['Cherbourg, France', 'Antipodes Islands'],
['Pago Pago, American Samoa', 'Zinder, Niger'],
['Barranquilla, Colombia', 'Christmas Island, Australia'],
['Doha, Qatar', 'Pitcairn Island'],
['Hue, Vietnam', 'Arequipa, Peru'],
['Da Nang, Vietnam', 'Arequipa, Peru'],
['Manila, Philippines', 'Cuiaba, Brazil'],
['Kuala Lumpur, Malaysia', 'Cuenca, Ecuador'],
['San Juan, Puerto Rico', 'Karratha, Australia'],
['Limerick, Ireland', 'Campbell Islands, New Zealand'],
['Arrecife, Lanzarote, Canary Islands', 'Norfolk Island'],
['Sharm el Sheikh, Egypt', 'Rapa Iti, French Polynesia'],
['Bangkok, Thailand', 'Lima, Peru'],
['Quito, Ecuador', 'Singapore'],
['Perth, Australia', 'Hamilton, Bermuda'],
['Montevideo, Uruguay', 'Seoul, South Korea'] ]
